<h1>Votre tableau de bord, <strong><?=htmlentities($_SESSION['login'])?></strong></h1>

<div class="bg-text">
	<h2>Vos informations</h2>

	<h3>Login : <strong><?=htmlentities($_SESSION['login'])?></strong></h3>
	<h3>Prénom : <strong><?=htmlentities($first_name)?></strong></h3>
	<h3>Nom : <strong><?=htmlentities($last_name)?></strong></h3>
	<h3>Poste : <strong><?=htmlentities($employment)?></strong></h3>
	<h3>Email : <strong><?=htmlentities($email)?></strong></h3>
	<h3>Téléphone : <strong><?=htmlentities($phone)?></strong></h3>

</div>

	<h3>Modifier les paramètres de votre compte :</h3>

	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-edit-user">Informations personnelles</button>

	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-edit-secure">Paramètres de sécurité</button>

	<?php require('apps/edit_user.php'); ?>
