<h1>Votre tableau de bord, <strong><?=htmlentities($_SESSION['login'])?></strong></h1>

	<h2>Vos informations</h2>
<div class="bg-text">

	<p>Login : <strong><?=htmlentities($_SESSION['login'])?></strong></p>
	<p>Prénom : <strong><?=htmlentities($first_name)?></strong></p>
	<p>Nom : <strong><?=htmlentities($last_name)?></strong></p>
	<p>Poste : <strong><?=htmlentities($employment)?></strong></p>
	<p>Email : <strong><?=htmlentities($email)?></strong></h3>
	<p>Téléphone : <strong><?=htmlentities($phone)?></strong></p>

</div>

	<h3>Modifier les paramètres de votre compte :</h3>

	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-edit-user">Informations personnelles</button>

	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-edit-secure">Paramètres de sécurité</button>

	<?php require('apps/edit_user.php'); ?>
