


<div class="test">



    <div class="row">
        <div class="col-md-12">
            
            <div class="alert alert-success">NOUVEAU TICKET A VALIDER</div>
            <table class="table">
                <thead>
                    <tr>
                        
                        <th>
                            Titre du ticket
                        </th>
                        <th>
                            Contenu du tickets
                        </th>
                          <th>
                           Auteur
                        </th>
                         <th>
                           Date de création
                        </th>
                          <th>
                           
                        </th>
                        
                    </tr>
                </thead>


<?php require('apps/tableau_tickets_a_valider.php');?>
                       
              

            </table>
        </div>
    </div>
  </div>
