<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Ticket Tac</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="register">Register <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="account">Account</a></li> -->
        <!-- <li><a href="list_user">list user</a></li> -->
      </ul>
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><button type="button" class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#modal-login">Connexion</button></li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <div class="container hidden-xs">
  <img src="public/images/logo-lg.png" alt="Bistrot Moderne"> -->
  <!-- <a href="#"><img src="public/images/footer.jpg" alt="Bistrot Moderne"></a> -->
<!-- </div>
<div class="container visible-xs text-center">
  <img src="public/images/logo-mobil.jpg" alt="Bistrot Moderne"> -->
  <!-- <a href="#"><img src="public/images/footer.jpg" alt="Bistrot Moderne"></a> -->
<!-- </div> -->




