<div class="row">
	<div class="col-xs-12">
		 <div class="classWithPad">
			<!-- <h2>Création de ticket</h2> -->
			<?php require('apps/creation.php'); ?>
		</div>
	</div>	
</div>
<div class="row">
	<div class="col-xs-12 col-sm-2">
		 <ul class="classWithPad sortableList" id="sortable0">
			<h2>En validation</h2>
			<?php require('apps/validation.php'); ?>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-3">
		 <ul class="classWithPad sortableList" id="sortable1" >
			<h2>A faire</h2>
			<?php require('apps/afaire.php'); ?>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-2">
		 <ul class="classWithPad sortableList" id="sortable2">
			<h2>En cours</h2>
			<?php require('apps/encours.php'); ?>
		</ul>
	</div>	
	<div class="col-xs-12 col-sm-2">
		 <ul class="classWithPad sortableList" id="sortable3">
			<h2>En test</h2>
			<?php require('apps/test.php'); ?>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-3">
		 <ul class="classWithPad sortableList" id="sortable4">
			<h2>Fait</h2>
			<?php require('apps/fait.php'); ?>
		</ul>
	</div>
</div>
<script>
$(function() {
    $( "ul.sortableList" ).sortable({
      connectWith: "ul"
    });
 
    $( "#sortable0, #sortable1, #sortable2, #sortable3, #sortable4" ).disableSelection();
  });
</script>