<div class="row">
	<div class="col-xs-12">
		 <div class="classWithPad">
			<h2>Création de ticket</h2>
			<?php require('apps/creation.php'); ?>
		</div>
	</div>	
</div>
<hr>
<div class="row">
	<div class="col-xs-4 col-sm-2">
		 <div class="classWithPad">
			<h2>En validation</h2>
			<?php require('apps/validation.php'); ?>
		</div>
	</div>
	<div class="col-xs-4 col-sm-2">
		 <div class="classWithPad">
			<h2>A faire</h2>
			<?php require('apps/afaire.php'); ?>
		</div>
	</div>
	<div class="col-xs-4 col-sm-2">
		 <div class="classWithPad">
			<h2>En cours</h2>
			<?php require('apps/encours.php'); ?>
		</div>
	</div>	
	<div class="col-xs-4 col-sm-2">
		 <div class="classWithPad">
			<h2>En test</h2>
			<?php require('apps/test.php'); ?>
		</div>
	</div>
	<div class="col-xs-4 col-sm-2">
		 <div class="classWithPad">
			<h2>Fait</h2>
			<?php require('apps/fait.php'); ?>
		</div>
	</div>
</div>