
<h1 class="text-center">Ticket Tac</h1>

<h2 class="text-center">Gestionnaire de tickets</h2>
<div class="login text-center">
	<form method="POST">
		<div class="form-group">
			<label for="login">Login</label>
			<input type="text" class="form-control" id="login" name="login" placeholder="Login">
		</div>
		<div class="form-group">
			<label for="password">Password</label>
			<input type="password" class="form-control" id="password" name="password" placeholder="Password">
		</div>
		<button type="submit" class="btn btn-success" name="action" value="login">Se connecter</button>
	</form>
</div>
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-register">Créer votre compte</button> -->

<?php require('apps/login.php'); ?>
