<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Ticket tac</title>
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Karla' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style-custom.css">
		<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

	</head>
	<body>
		<div class="scrollup"></div>
		<?php require('apps/header.php'); ?>
		<?php require('apps/content.php'); ?>
		<?php require('apps/footer.php'); ?>
		<script type="text/javascript" src="public/scripts/jquery.min.js"></script>
		<script type="text/javascript" src="public/scripts/bootstrap.min.js"></script>
		<script type="text/javascript" src="public/scripts/jquery-ui.min.js"></script>
		<script type="text/javascript" src="public/scripts/jquery.bootstrap-growl.js"></script>
		<script type="text/javascript" src="public/scripts/js-custom.js"></script>
		<script type="text/javascript" src="public/scripts/script.js"></script>
	</body>
</html>
